spring:
  application.name: shopping-order-service
  jackson:
    serialization:
      indent-output: true

server:
  servlet:
    context-path: /
  port: 8083
---
#DOCKER CONFIGURATION
spring:
  profiles:
    active:
      - docker
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        hostname: shopping-order-service
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckPath: /actuator/health
        healthCheckInterval: 50s
---
#oauth2 configuration
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9090/oauth/check_token
    client:
      client-id: web
      client-secret: pin
   


    
  